In [1]:
import torch

In [3]:
# 0または1埋めされたdata

a = torch.zeros([2, 4], dtype=torch.int32)
print(a)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


In [4]:
b = torch.ones([2, 3, 3])
print(b)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


In [13]:
# for GPU

device = torch.device('cuda:0')
c = torch.ones([2, 3, 3], dtype=torch.float64, device=device)
print(c)


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], device='cuda:0', dtype=torch.float64)


In [14]:
d = torch.ones([2, 3, 3], dtype=torch.float64)
d.to(device)
print(d)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], dtype=torch.float64)


In [16]:
# grad

x = torch.tensor(2.5, requires_grad=True)
y = 4.5*x + 2
y.backward()
print(y)
print(x)
print(x.grad)

tensor(13.2500, grad_fn=<AddBackward0>)
tensor(2.5000, requires_grad=True)
tensor(4.5000)


In [17]:
print(4.5*2.5 +2)

13.25


In [19]:
# ndarray => Tensor
import numpy as np

a = np.random.randn(2, 3)
b = torch.from_numpy(a)
print(a)
print(b)

[[ 1.79322848 -2.01226166  0.49464804]
 [-0.23600675 -1.13500335  1.32774189]]
tensor([[ 1.7932, -2.0123,  0.4946],
        [-0.2360, -1.1350,  1.3277]], dtype=torch.float64)


In [20]:
# carefully

a = np.random.randn(3).astype(np.float32)
print(a)
b = torch.from_numpy(a)
b[0] = -1
print(a)

[ 0.53024936  0.02313642 -0.841172  ]
[-1.          0.02313642 -0.841172  ]


In [21]:
a = np.random.randn(3).astype(np.float32)
print(a)
b = torch.from_numpy(a.copy())
b[0] = -1
print(a)

[ 0.08494783  0.1738401  -0.5703047 ]
[ 0.08494783  0.1738401  -0.5703047 ]


In [22]:
# Tensor => ndarray

a = torch.tensor(np.array([[1,2,3,4], [5,6,7,8]]))
b = a.numpy()
print(a)
print(b)


tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=torch.int32)
[[1 2 3 4]
 [5 6 7 8]]
